export const API_ENDPOINTS = {
  LOGIN: '/api/auth/login',
  REGISTER: '/api/auth/register',
  VERIFY_OTP: '/api/auth/verify-otp',
  RESEND_OTP: '/api/auth/resend-otp',
  LOGOUT: '/api/auth/logout',
  FORGET_PASSWORD: '/api/forget-password.json',
  CATEGORIES: '/api/categories.json',
  CATEGORIES_DYNAMIC: '/api/categories',
  DIETARY: '/api/dietary.json',
  BRANDS: '/api/brands.json',
  PRODUCTS: '/api/products.json',
  PRODUCT: '/api/product.json',
  RELATED_PRODUCTS: '/api/related_products.json',
  RELATED_PRODUCTS_DYNAMIC: (slug: string) => `/api/products/${slug}/related`,
  FLASH_SELL_PRODUCTS: '/api/products_flash_sell.json',
  BEST_SELLER_PRODUCTS: '/api/products_best_seller.json',
  BEST_SELLER_GROCERY_PRODUCTS: '/api/products_best_seller_grocery.json',
  POPULAR_PRODUCTS: '/api/products_popular.json',
  COOKIES_PRODUCTS: '/api/products_cookies.json',
  CHIPS_PRODUCTS: '/api/products_chips.json',
  POPCORN_JERKY_PRODUCTS: '/api/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: '/api/products_fresh_vegetables.json',
  SEARCH: '/api/search.json',
  ORDERS: '/api/orders.json',
  ORDER: '/api/order.json',
  ORDER_STATUS: '/api/order-status.json',
  ADDRESS: '/api/address.json',
  PAYMENT: '/api/payment.json',
  PAYMENT_METHODS: '/api/payment-methods',
  PAYMENT_METHODS_SETUP_INTENT: '/api/payment-methods/setup-intent',
  PAYMENT_METHODS_CONFIRM: '/api/payment-methods/confirm',
  CONTACT: '/api/contact.json',
  CONTACT_NUMBERS: '/api/contact-numbers',
  PROFILE: '/api/profile',
  PROFILE_PHONE: '/api/profile/phone',
  PROFILE_PASSWORD: '/api/profile/password',
  PROFILE_EMAIL_VERIFY_OTP: '/api/profile/email/verify-otp',
  PROFILE_EMAIL_RESEND_OTP: '/api/profile/email/resend-otp',
  PROFILE_EMAIL_CANCEL: '/api/profile/email/cancel',
  SHOP: '/api/shop.json',
  SHOPS: '/api/shops.json',
  WISHLIST: '/api/wishlist',
  WISHLIST_IDS: '/api/wishlist/ids',
  COUNTRIES: '/api/countries',
  ADDRESSES: '/api/addresses',
  ORDERS_DYNAMIC: '/api/orders',
  ORDER_DYNAMIC: (id: number) => `/api/orders/${id}`,
  ORDER_INVOICE: (id: number) => `/api/orders/${id}/invoice`,
  ORDER_INVOICE_GUEST: (id: number) => `/api/orders/${id}/invoice/guest`,
  COUPON_APPLY: '/api/coupons/apply',
  SHIPPING_QUOTE: '/api/shipping/quote',

  // Laravel dynamic product endpoints (prefixed with /api)
  PRODUCTS_DYNAMIC: '/api/products',
  POPULAR_PRODUCTS_DYNAMIC: '/api/products/popular',
  BEST_SELLER_PRODUCTS_DYNAMIC: '/api/products/best-seller',
};
